# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/filip/Projects/xilinx/Basys3_Master.xdc

# Block Designs: bd/microblaze_MCU/microblaze_MCU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU || ORIG_REF_NAME==microblaze_MCU} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_microblaze_0_0/microblaze_MCU_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_microblaze_0_0 || ORIG_REF_NAME==microblaze_MCU_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_dlmb_v10_0/microblaze_MCU_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_dlmb_v10_0 || ORIG_REF_NAME==microblaze_MCU_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_ilmb_v10_0/microblaze_MCU_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_ilmb_v10_0 || ORIG_REF_NAME==microblaze_MCU_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_dlmb_bram_if_cntlr_0/microblaze_MCU_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_MCU_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_ilmb_bram_if_cntlr_0/microblaze_MCU_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_MCU_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_lmb_bram_0/microblaze_MCU_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_lmb_bram_0 || ORIG_REF_NAME==microblaze_MCU_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_mdm_1_0/microblaze_MCU_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_mdm_1_0 || ORIG_REF_NAME==microblaze_MCU_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_clk_wiz_1_0/microblaze_MCU_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_clk_wiz_1_0 || ORIG_REF_NAME==microblaze_MCU_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_rst_clk_wiz_1_100M_0/microblaze_MCU_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblaze_MCU_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_vga_basic_control_0_0/microblaze_MCU_vga_basic_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_vga_basic_control_0_0 || ORIG_REF_NAME==microblaze_MCU_vga_basic_control_0_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_microblaze_0_axi_periph_0/microblaze_MCU_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_MCU_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_rst_clk_wiz_1_40M_0/microblaze_MCU_rst_clk_wiz_1_40M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_rst_clk_wiz_1_40M_0 || ORIG_REF_NAME==microblaze_MCU_rst_clk_wiz_1_40M_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_xbar_0/microblaze_MCU_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_xbar_0 || ORIG_REF_NAME==microblaze_MCU_xbar_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_ps2_keyboard_0_0/microblaze_MCU_ps2_keyboard_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_ps2_keyboard_0_0 || ORIG_REF_NAME==microblaze_MCU_ps2_keyboard_0_0} -quiet] -quiet

# IP: bd/microblaze_MCU/ip/microblaze_MCU_auto_cc_0/microblaze_MCU_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_MCU_auto_cc_0 || ORIG_REF_NAME==microblaze_MCU_auto_cc_0} -quiet] -quiet

# XDC: bd/microblaze_MCU/microblaze_MCU_ooc.xdc
